### PR TITLE
Added a simple linux install guide

### PR DESCRIPTION
**Pull request by Nuclear-Squid**
Hi, like I promised a few days ago, I wrote a small linux install guide for kanata. It explains how to install kanata and run it as a daemon. What do you think about it ?

### CODE REVIEW

**Comment by Nuclear-Squid** [comment]
Wait, hold on my branch is a commit behind. **Don’t** merge

**Comment by fabi1cazenave** [comment]
Oh, thanks for this contribution. May I suggest to put it in the kanata/README file ?

In the long run, I’d like to propose several implementations — KMonad, Karabiner, Keyd… — so there’s one directory per app. And app-specific instructions would fit nicely there.

**Comment by Nuclear-Squid** [comment]
Oh That is a great Idea, I’ll fix that right away!

**Comment by Nuclear-Squid** [comment]
Now it replaces the one-line install guide in kanata/readme.md

**Comment by fabi1cazenave** [comment]
Thanks for the good work !

**Pull request merged**
